# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bb4aed2067522d09aeffc6ad149e9c882c92a1d72fd01b4fdd992cf013f185348d335686c0a0a7da48b80f6e1b10ca26dd1f43ad47edffdba3576f3e3dd1cdd

test:
  secret_key_base: 3184d196ad2db740dba49d369b010bf1766e1fd9c44a99a2284d54c377ffa4060afaa5e0a1f8a918f87a0f5bf4598473842963b99950ae823a9f161f9fca2944

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
